name: plseg
channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.8
    - numpy
    - scipy
    - scikit-image
    - imageio
    - Flask
    - tqdm
    - pip
    - pip:
      - gco-wrapper
